# Generated by Django 6.0.6 on 2026-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_achievements_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='office_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
