# Generated by Django 6.0.6 on 2026-07-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_department_profile_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('coordinator', 'Coordinator'), ('employer', 'Employer')], default='student', max_length=20),
        ),
    ]
