# Generated by Django 6.0.6 on 2026-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_company_address_profile_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_account_active',
            field=models.BooleanField(default=True),
        ),
    ]
