# Generated by Django 6.0.6 on 2026-07-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_is_account_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_permanently_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
