# Generated by Django 6.0.6 on 2026-07-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability',
            field=models.CharField(choices=[('immediately', 'Immediately'), ('15_days', 'Within 15 Days'), ('30_days', 'Within 30 Days'), ('60_days', 'Within 60 Days')], default='immediately', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
