# Generated by Django 6.0.6 on 2026-07-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_availability_application_cover_letter_and_more'),
        ('placements', '0001_initial'),
        ('profiles', '0003_profile_achievements_profile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.placement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'unique_together': {('student', 'placement')},
            },
        ),
    ]
