# Generated by Django 6.0.6 on 2026-07-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_savedplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('resume_reviewed', 'Resume Reviewed'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('rejected', 'Rejected')], default='applied', max_length=30),
        ),
    ]
