# Generated by Django 6.0.6 on 2026-07-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_status'),
        ('placements', '0002_placement_company_about_placement_company_website_and_more'),
        ('profiles', '0004_profile_department_profile_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('oa_difficulty', models.PositiveSmallIntegerField()),
                ('interview_difficulty', models.PositiveSmallIntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.placement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'unique_together': {('student', 'placement')},
            },
        ),
    ]
