# Generated by Django 6.0.6 on 2026-07-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_supportticket_ticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
