# Generated by Django 6.0.6 on 2026-07-07 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_referralopportunity_referralrequest'),
        ('profiles', '0006_profile_company_address_profile_company_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('coordinator', 'Coordinator'), ('employer', 'Employer')], max_length=20)),
                ('post_type', models.CharField(choices=[('achievement', 'Achievement'), ('interview', 'Interview Experience'), ('career_question', 'Career Question'), ('career_tip', 'Career Tip'), ('placement_drive', 'Placement Drive'), ('announcement', 'Announcement'), ('deadline', 'Deadline'), ('preparation_tip', 'Preparation Tip'), ('hiring', 'Hiring'), ('internship', 'Internship'), ('company_update', 'Company Update'), ('recruitment_tip', 'Recruitment Tip')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
