# Generated by Django 6.0.6 on 2026-07-07 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_communitycomment'),
        ('profiles', '0006_profile_company_address_profile_company_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
