# Generated by Django 6.0.6 on 2026-07-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_savedcommunitypost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitypost',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='communitypost',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
