# Generated by Django 6.0.6 on 2026-07-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_applicationstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='new_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('resume_reviewed', 'Resume Reviewed'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('rejected', 'Rejected')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='old_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('resume_reviewed', 'Resume Reviewed'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('rejected', 'Rejected')], max_length=30),
        ),
    ]
