services:
  - type: web
    name: placenexus
    env: python

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate

    startCommand: gunicorn config.wsgi

    envVars:
      - key: DEBUG
        value: False