# Generated by Django 6.0.6 on 2026-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='company_about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='eligibility',
            field=models.TextField(blank=True, help_text='Eligibility Criteria'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
