# Generated by Django 6.0.6 on 2026-07-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_placement_company_about_placement_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
