# Generated by Django 6.0.6 on 2026-07-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_placement_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
    ]
