# Generated by Django 6.0.6 on 2026-07-06 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_placement_required_skills'),
        ('profiles', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
