# Generated by Django 6.0.6 on 2026-07-06 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_placement_employer'),
        ('profiles', '0006_profile_company_address_profile_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_placements', to='profiles.profile'),
        ),
    ]
