# Generated by Django 6.0.6 on 2026-07-13 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0006_placement_created_by'),
        ('profiles', '0008_profile_is_permanently_deactivated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Data Science', 'Data Science'), ('Cyber Security', 'Cyber Security'), ('Information Technology', 'Information Technology'), ('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Electrical', 'Electrical'), ('Finance', 'Finance'), ('MBA', 'MBA')], max_length=100)),
                ('package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateField()),
                ('required_skills', models.TextField()),
                ('eligibility', models.TextField()),
                ('description', models.TextField()),
                ('company_about', models.TextField(blank=True)),
                ('company_website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('needs_changes', 'Needs Changes'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='pending', max_length=20)),
                ('coordinator_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_requests', to='profiles.profile')),
            ],
        ),
    ]
