# Generated by Django 6.0.6 on 2026-07-13 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0007_placementrequest'),
        ('profiles', '0008_profile_is_permanently_deactivated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('needs_changes', 'Needs Changes'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_reviews', to='profiles.profile')),
                ('placement_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='placements.placementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
                ('placement_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='placements.placementrequest')),
            ],
            options={
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='ReviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='placements.placementreview')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
