# Generated by Django 6.0.6 on 2026-07-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0008_placementreview_placementrevision_reviewmessage'),
        ('profiles', '0008_profile_is_permanently_deactivated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_banner', models.ImageField(blank=True, null=True, upload_to='company_banners/')),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('company_size', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to='profiles.profile')),
            ],
        ),
    ]
